import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Container, Heading } from "@chakra-ui/react";

import { Layout } from "../components/Layout";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <Layout>
      <Head>
        <title>OpenBadge to ION VC Converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Heading my="8">OpenBadge to ION VC Converter</Heading>
        <Button
          w="full"
          my="4"
          colorScheme="blue"
          onClick={() => router.push("/issue")}
        >
          Issue VC
        </Button>
        <Button
          w="full"
          colorScheme="teal"
          onClick={() => router.push("/verify")}
        >
          Verify VC
        </Button>
      </Container>
    </Layout>
  );
};

export default Home;
